## Project 8 - Writing Functions in Python - Sarah Liu

In [ ]:
'''
/anvil/projects/tdm/data/spotify/taylor_swift_discography_updated.csv
/anvil/projects/tdm/data/youtube/most_subscribed_youtube_channels.csv
'''

# Question 1

In [4]:
import pandas as pd

# Load the dataset
ts_songs = pd.read_csv('/anvil/projects/tdm/data/spotify/taylor_swift_discography_updated.csv', sep=';')
pd.set_option('display.max_columns', None)

ts_songs.head()

,ID,track_name,track_musical_genre,track_type,duration_ms,feature,track_videoclip,videoclip_views,spotify_streams,spotify_global_peak,album,track_number,album_musical_genre,album_type,release_date,album_physical_sales,track_lyrics,track_theme,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
0,0,Fortnight (feat. Post Malone),Synth Pop,Single,228965,Post Malone,No,0,648525069,1,The Tortured Poets Department: The Anthology,1,Pop,Compilation/Deluxe,19/4/2024,0,I was supposed to be sent away But they forgot...,Complicated love/Looking for love,spotify:track:6dODwocEuGzHAavXqTbwHv,0.5020,0.504,0.386,1.53e-05,0.0961,-10.976,0.0308,192.004,0.281
1,1,The Tortured Poets Department,Synth Pop,B-Side,293048,No,No,0,206954130,6,The Tortured Poets Department: The Anthology,2,Pop,Compilation/Deluxe,19/4/2024,0,You left your typewriter at my apartment Strai...,Complicated love/Looking for love,spotify:track:4PdLaGZubp4lghChqp8erB,0.0483,0.604,0.428,0.0,0.1260,-8.441,0.0255,110.259,0.292
2,2,My Boy Only Breaks His Favorite Toys,Synth Pop,B-Side,203801,No,No,0,238016975,7,The Tortured Poets Department: The Anthology,3,Pop,Compilation/Deluxe,19/4/2024,0,"Oh, here we go again. The voices in his head C...",Broken heart/Sadness,spotify:track:7uGYWMwRy24dm7RUDDhUlD,0.1370,0.596,0.563,0.0,0.3020,-7.362,0.0269,97.073,0.481
3,3,Down Bad,R&B,B-Side,261228,No,No,0,318375377,2,The Tortured Poets Department: The Anthology,4,Pop,Compilation/Deluxe,19/4/2024,0,Did you really beam me up? In a cloud of spark...,Broken heart/Sadness,spotify:track:1kbEbBdEgQdQeLXCJh28pJ,0.5600,0.541,0.366,"1,00E-06",0.0946,-10.412,0.0748,159.707,0.168
4,4,"So Long, London",Synth Pop,B-Side,262974,No,No,0,253712712,4,The Tortured Poets Department: The Anthology,5,Pop,Compilation/Deluxe,19/4/2024,0,I saw in my mind fairy lights through the mist...,Broken heart/Sadness,spotify:track:7wAkQFShJ27V8362MqevQr,0.7300,0.423,0.533,0.00264,0.0816,-11.388,0.3220,160.218,0.248

In [5]:
# 1.1
# maximum energy level
max_energy = ts_songs['energy'].max()
print(f"The maximum energy level is: {max_energy}")

# minimum energy level
min_energy = ts_songs['energy'].min()
print(f"The minimum energy level is: {min_energy}")

The maximum energy level is: 0.95
The minimum energy level is: 0.118

In [7]:
def find_songs_with_energy(input_df, threshold):
    my_output = input_df[input_df["energy"] >= threshold]
    return my_output

# median energy
my_median = ts_songs['energy'].median()
# 1.2 songs >= median 
high_energy_df = find_songs_with_energy(ts_songs, my_median)
print(f"There are {len(high_energy_df)} songs with energy greater than or equal to the median.")

There are 289 songs with energy greater than or equal to the median.

In [8]:
# 1.3 
def find_songs_by_album(input_df, album_name):
    album_songs = input_df[input_df["album"] == album_name]
    return album_songs

# test func
ttpd_anthology = find_songs_by_album(ts_songs, "The Tortured Poets Department: The Anthology")
print(f"Number of rows for the anthology: {len(ttpd_anthology)}")
ttpd_anthology.head()

Number of rows for the anthology: 31

,ID,track_name,track_musical_genre,track_type,duration_ms,feature,track_videoclip,videoclip_views,spotify_streams,spotify_global_peak,album,track_number,album_musical_genre,album_type,release_date,album_physical_sales,track_lyrics,track_theme,uri,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence
0,0,Fortnight (feat. Post Malone),Synth Pop,Single,228965,Post Malone,No,0,648525069,1,The Tortured Poets Department: The Anthology,1,Pop,Compilation/Deluxe,19/4/2024,0,I was supposed to be sent away But they forgot...,Complicated love/Looking for love,spotify:track:6dODwocEuGzHAavXqTbwHv,0.5020,0.504,0.386,1.53e-05,0.0961,-10.976,0.0308,192.004,0.281
1,1,The Tortured Poets Department,Synth Pop,B-Side,293048,No,No,0,206954130,6,The Tortured Poets Department: The Anthology,2,Pop,Compilation/Deluxe,19/4/2024,0,You left your typewriter at my apartment Strai...,Complicated love/Looking for love,spotify:track:4PdLaGZubp4lghChqp8erB,0.0483,0.604,0.428,0.0,0.1260,-8.441,0.0255,110.259,0.292
2,2,My Boy Only Breaks His Favorite Toys,Synth Pop,B-Side,203801,No,No,0,238016975,7,The Tortured Poets Department: The Anthology,3,Pop,Compilation/Deluxe,19/4/2024,0,"Oh, here we go again. The voices in his head C...",Broken heart/Sadness,spotify:track:7uGYWMwRy24dm7RUDDhUlD,0.1370,0.596,0.563,0.0,0.3020,-7.362,0.0269,97.073,0.481
3,3,Down Bad,R&B,B-Side,261228,No,No,0,318375377,2,The Tortured Poets Department: The Anthology,4,Pop,Compilation/Deluxe,19/4/2024,0,Did you really beam me up? In a cloud of spark...,Broken heart/Sadness,spotify:track:1kbEbBdEgQdQeLXCJh28pJ,0.5600,0.541,0.366,"1,00E-06",0.0946,-10.412,0.0748,159.707,0.168
4,4,"So Long, London",Synth Pop,B-Side,262974,No,No,0,253712712,4,The Tortured Poets Department: The Anthology,5,Pop,Compilation/Deluxe,19/4/2024,0,I saw in my mind fairy lights through the mist...,Broken heart/Sadness,spotify:track:7wAkQFShJ27V8362MqevQr,0.7300,0.423,0.533,0.00264,0.0816,-11.388,0.3220,160.218,0.248

# Question 2

In [9]:
# 2.1 
# milliseconds to seconds
ts_songs['duration_sec'] = ts_songs['duration_ms'] / 1000
# seconds to minutes
ts_songs['duration_min'] = ts_songs['duration_sec'] / 60
ts_songs[['track_name', 'duration_ms', 'duration_min']].head()

                             track_name  duration_ms  duration_min
0         Fortnight (feat. Post Malone)       228965      3.816083
1         The Tortured Poets Department       293048      4.884133
2  My Boy Only Breaks His Favorite Toys       203801      3.396683
3                              Down Bad       261228      4.353800
4                       So Long, London       262974      4.382900

In [10]:
def find_albums_by_time(input_df, input_min_duration):
    total_by_album = input_df.groupby("album")["duration_min"].sum().reset_index()
    long_albums = total_by_album[total_by_album["duration_min"] > input_min_duration]
    return long_albums

# Test 2.2 -> albums longer than 80 minutes
albums_80 = find_albums_by_time(ts_songs, 80)
print("Albums longer than 80 minutes:")
print(albums_80)

# Test 2.3 -> albums longer than 120 minutes
albums_120 = find_albums_by_time(ts_songs, 120)
print("\nAlbums longer than 120 minutes:")
print(albums_120)

Albums longer than 80 minutes:
                                                album  duration_min
3                    1989 (Taylor's Version) [Deluxe]     81.301667
5                         Fearless (Taylor's Version)    106.541500
11                   Midnights (The Til Dawn Edition)     80.586083
13                               Red (Deluxe Edition)     90.217667
14                             Red (Taylor's Version)    130.663833
16                         Speak Now (Deluxe Edition)     91.840117
17                       Speak Now (Taylor's Version)    104.734183
21       The Tortured Poets Department: The Anthology    122.645733
26  folklore: the long pond studio sessions (from ...    134.704517
28     reputation Stadium Tour Surprise Song Playlist    186.266467

Albums longer than 120 minutes:
                                                album  duration_min
14                             Red (Taylor's Version)    130.663833
21       The Tortured Poets Department: The Anthology    122.645733
26  folklore: the long pond studio sessions (from ...    134.704517
28     reputation Stadium Tour Surprise Song Playlist    186.266467

# Question 3

In [11]:
# 3.1 set the lower/upper album length thresholds
lower_threshold = 30
upper_threshold = 80

                              album  duration_min category
0                              1989     48.797733   Medium
1             1989 (Deluxe Edition)     68.760800   Medium
2           1989 (Taylor's Version)     77.972117   Medium
3  1989 (Taylor's Version) [Deluxe]     81.301667     Long
4                          Fearless     53.547900   Medium

In [12]:
# 3.2
def albums_by_length(df, lower_threshold, upper_threshold):
    total_by_album = df.groupby("album")["duration_min"].sum().reset_index()
    def classify(duration):
        if duration < lower_threshold:
            return "Short"
        elif duration > upper_threshold:
            return "Long"
        else:
            return "Medium"
    total_by_album["category"] = total_by_album["duration_min"].apply(classify)
    return total_by_album

# 3.3
final_albums_df = albums_by_length(ts_songs, lower_threshold=30, upper_threshold=80)
print(final_albums_df)

                                                album  duration_min category
0                                                1989     48.797733   Medium
1                               1989 (Deluxe Edition)     68.760800   Medium
2                             1989 (Taylor's Version)     77.972117   Medium
3                    1989 (Taylor's Version) [Deluxe]     81.301667     Long
4                                            Fearless     53.547900   Medium
5                         Fearless (Taylor's Version)    106.541500     Long
6                           Fearless Platinum Edition     79.443683   Medium
7               Live From Clear Channel Stripped 2008     27.929250    Short
8                                               Lover     61.856350   Medium
9                                           Midnights     44.138967   Medium
10                            Midnights (3am Edition)     69.487733   Medium
11                   Midnights (The Til Dawn Edition)     80.586083     Long
12                                                Red     64.923233   Medium
13                               Red (Deluxe Edition)     90.217667     Long
14                             Red (Taylor's Version)    130.663833     Long
15                                          Speak Now     67.032800   Medium
16                         Speak Now (Deluxe Edition)     91.840117     Long
17                       Speak Now (Taylor's Version)    104.734183     Long
18                          Speak Now World Tour Live     79.232317   Medium
19                                       Taylor Swift     53.492783   Medium
20                      The Tortured Poets Department     65.261750   Medium
21       The Tortured Poets Department: The Anthology    122.645733     Long
22                                           evermore     60.753500   Medium
23                          evermore (deluxe version)     69.081267   Medium
24                                           folklore     63.609783   Medium
25                          folklore (deluxe version)     67.139933   Medium
26  folklore: the long pond studio sessions (from ...    134.704517     Long
27                                         reputation     55.755000   Medium
28     reputation Stadium Tour Surprise Song Playlist    186.266467     Long

# Question 4

In [13]:
youtubers = pd.read_csv('/anvil/projects/tdm/data/youtube/most_subscribed_youtube_channels.csv')

# 4.1 make numeric and clean
youtubers['video_count2'] = youtubers['video count'].str.replace(",", "", regex=False)
youtubers['video_count2'] = pd.to_numeric(youtubers['video_count2'])
youtubers[['Youtuber', 'video count', 'video_count2']].head()

                     Youtuber video count  video_count2
0                    T-Series      17,317         17317
1              YouTube Movies           0             0
2  Cocomelon - Nursery Rhymes         786           786
3                   SET India      91,271         91271
4                       Music           0             0

In [14]:
# 4.2 count per category
category_video_counts = youtubers.groupby('category')['video_count2'].sum()

print("Total videos per category:")
print(category_video_counts)

Total videos per category:
category
Autos & Vehicles            2874
Comedy                     93562
Education                 124727
Entertainment            2674176
Film & Animation          133319
Gaming                    427292
Howto & Style              81419
Movies                      5576
Music                     510337
News & Politics          2754693
Nonprofits & Activism     188445
People & Blogs           1045091
Pets & Animals             23960
Science & Technology       36622
Shows                     283027
Sports                    140464
Trailers                   13613
Travel & Events              632
Name: video_count2, dtype: int64

In [15]:
# 4.3 show grouped_counts
gm_subset = youtubers[youtubers["category"].isin(["Gaming", "Music"])]
# group by category + started, sum and unstack
grouped_counts = gm_subset.groupby(["category", "started"])["video_count2"].sum().unstack()
print("Grouped counts (Gaming vs Music by Year):")
grouped_counts

Grouped counts (Gaming vs Music by Year):

started,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
category,,,,,,,,,,,,,,,,
Gaming,17878.0,163116.0,11967.0,16356.0,15342.0,9998.0,27421.0,72858.0,32267.0,31332.0,7342.0,7903.0,9302.0,2952.0,1126.0,132.0
Music,1446.0,36423.0,51621.0,33451.0,16392.0,31766.0,89353.0,44299.0,71681.0,119692.0,5447.0,8477.0,156.0,121.0,12.0,NaN

# Question 5

In [16]:
# 5.1 
# clean the subscribers column
youtubers['subscribers2'] = youtubers['subscribers'].str.replace(",", "", regex=False)
youtubers['subscribers2'] = pd.to_numeric(youtubers['subscribers2'])

def top_youtuber_by_genre(df, genre):
    genre_rows = df[df["category"] == genre]
    top_index = genre_rows['subscribers2'].idxmax()
    return genre_rows.loc[top_index]

# 5.1
top_gaming = top_youtuber_by_genre(youtubers, "Gaming")
print(top_gaming)

rank                         6
Youtuber             PewDiePie
subscribers        111,000,000
video views     28,469,458,228
video count              4,497
category                Gaming
started                   2010
video_count2              4497
subscribers2         111000000
Name: 5, dtype: object

In [17]:
# 5.2
top_music = top_youtuber_by_genre(youtubers, "Music")
print(top_music[['Youtuber', 'subscribers2']])

Youtuber         T-Series
subscribers2    222000000
Name: 0, dtype: object

In [18]:
# 5.3 the current top youtuber is Mr.Beast with over 400 mil subs whilew pewdiepie was the top youtuber 3 years ago when gaming was more popular